package com.example

enum class Expenses(var title: String) {
    CLOTHES("clothes"),
    WORKOUT("workout"),
    REMONT("remont"),
    HOME("home"),
    RESTAURANT("restaurant"),
    TOK("tok"),
    VODA("voda"),
    TOPLO("toplo"),
    VHOD("vhod"),
    TELEFON("telefon"),
    INTERNET("internet"),
    PUBLIC("public"),
    TAXI("taxi"),
    CAR("car"),
    POSUDA("posuda"),
    TRAVEL("travel"),
    GIFTS("gifts"),
    SNACKS("snacks"),
    MEDICINE("medicine"),
    HIGIEN("higien"),
    OTHER("other"),
    DOMPOTREBI("domPotrebi"),
    CLEAN("clean"),
    WASH("wash"),
    MACHOVE("machove"),
    FURNITURE("furniture"),
    TEHNIKA("tehnika"),
    EDUCATION("education"),
    ENTERTAINMENT("entertainment"),
    SUBSCRIPTIONS("subscriptions"),
    TATTOO("tattoo"),
    TOYS("toys")
}